name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch: 
  
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install depencies
        run: |
          cd $GITHUB_WORKSPACE
      - name: Run Tests
        run: python -m unittest tests.py
        
        
  sending_message:
        runs-on: ubuntu-latest
        
        steps:
          - name: "Telegram Notification, when test is successed"
            uses: "appleboy/telegram-action@master"
            if: ${{ success() }}
            with:
              to: ${{ secrets.TP2_CHATID }}
              token: ${{ secrets.TP2_TOKEN }}
              args: Все ок
